name: Build CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install meson sassc

    - name: Build, Test and Install
      run: |
        meson build -Dgnome-shell-gresource=true -Dmate=true -Dmate-dark=true -Dubuntu-unity=true -Dxfwm4=true -Dcinnamon-shell=true -Dcinnamon=true -Dcinnamon-dark=true
        meson test -C build -v
        ninja -C build install
