name: Build CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Yaru
      uses: actions/checkout@v3

    - name: Check sources structure
      run: |
        # No symlinks should be in icons sources, they should be handled through lists
        test -z "$(find icons/src/{fullcolor,scalable} -type l)"

    - name: Install dependencies
      run: |
        sudo apt install sassc python3-pip
        sudo pip3 install meson ninja

    - name: Configure
      run: |
        meson _build \
          -Dgnome-shell-gresource=true \
          -Dmate=true \
          -Dmate-dark=true \
          -Dubuntu-unity=true \
          -Dxfwm4=true \
          -Dcinnamon-shell=true \
          -Dcinnamon=true \
          -Dcinnamon-dark=true

    - name: Build
      run: |
        ninja -C _build

    - name: Test
      run: |
        meson test -C _build

    - name: Install
      run: |
        ninja -C _build install

    - name: Archiving meson logs
      uses: actions/upload-artifact@v3
      with:
        name: meson-logs
        path: _build/meson-logs
